// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlEBMvNo4O9H2bCl3gwcRVp2VElDdQIh4',
    appId: '1:149120134047:android:1118bfa932ccaddd8e2baa',
    messagingSenderId: '149120134047',
    projectId: 'coffee-brew-6c73b',
    storageBucket: 'coffee-brew-6c73b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZWUvxiqcH-GbHWgdmDzZQKeyzxLeIPJc',
    appId: '1:149120134047:ios:749c280c99003fe48e2baa',
    messagingSenderId: '149120134047',
    projectId: 'coffee-brew-6c73b',
    storageBucket: 'coffee-brew-6c73b.appspot.com',
    iosClientId: '149120134047-se2mqdclo9e91ehotio3lua6ag488bed.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeBrew',
  );
}
